### ISSUE TITLE
Add transmission-mode sample calculations to xraydb?

### ISSUE THREAD

**Issue by easyXAFS** [xraypy/XrayDB#15]
XAFSmass (https://github.com/kklmn/XAFSmass) provides a nice GUI interface for calculations of transmission-mode XAFS samples. However it doesn't have a great programmatic API.

The necessary backend for these calculations is already neatly done in xraydb so it is fairly straightforward to implement. I am wondering if there would be interest to include similar calculations into xraydb. 

```python
import xraydb
import numpy as np


def analyze_absorbance_from_formula(formula, energy, area=None):
    """
    Example:
        formula = {'Re': 1, 'O': 2}
        energy = xraydb.xray_edge('Re', 'L2').energy
        area = (1.3 / 2) ** 2 * np.pi = 1.33 cm^2
    """
    mol_weight = sum([v * xraydb.atomic_mass(k) for k, v in formula.items()])
    mass_fracs = {k: v * xraydb.atomic_mass(k) / mol_weight for k, v in formula.items()}
    pre_edge = np.linspace(energy - 200, energy - 50, 100)
    mu_tot = sum([xraydb.mu_elam(k, energy + 50) * v for k, v in mass_fracs.items()])
    rho_d = 2.6 / mu_tot

    absorbance_steps = {}
    for el in formula.keys():
        coeffs = np.polyfit(pre_edge, xraydb.mu_elam(el, pre_edge), 3)
        extrapolated = sum([c * (energy + 50) ** (len(coeffs) - 1 - i) for i, c in enumerate(coeffs)])
        absorbance_steps[el] = (xraydb.mu_elam(el, energy + 50) - extrapolated) * mass_fracs[el] * rho_d

    results = {}
    results['mass_fractions'] = mass_fracs
    results['absorbance_steps'] = absorbance_steps

    if area is not None:
        mass_total = rho_d * area * 1000 # mg
        results['mass_total(mg)'] = mass_total
        results['mass_components(mg)'] = {k: v * mass_total for k, v in mass_fracs.items()}

    return results


def analyze_absorbance_from_mass_fractions(mass_fracs, energy, area=None):
    """
    Example:
        mass_fracs = {'Re': 0.85, 'O': 0.15}
        energy = xraydb.xray_edge('Re', 'L2').energy
        area = (1.3 / 2) ** 2 * np.pi = 1.33 cm^2
    """
    pre_edge = np.linspace(energy - 200, energy - 50, 100)
    mu_tot = sum([xraydb.mu_elam(k, energy + 50) * v for k, v in mass_fracs.items()])
    rho_d = 2.6 / mu_tot

    absorbance_steps = {}
    for el in mass_fracs.keys():
        coeffs = np.polyfit(pre_edge, xraydb.mu_elam(el, pre_edge), 3)
        extrapolated = sum([c * (energy + 50) ** (len(coeffs) - 1 - i) for i, c in enumerate(coeffs)])
        absorbance_steps[el] = (xraydb.mu_elam(el, energy + 50) - extrapolated) * mass_fracs[el] * rho_d

    results = {}
    results['mass_fractions'] = mass_fracs
    results['absorbance_steps'] = absorbance_steps

    if area is not None:
        mass_total = rho_d * area * 1000 # mg
        results['mass_total(mg)'] = mass_total
        results['mass_components(mg)'] = {k: v * mass_total for k, v in mass_fracs.items()}

    return results


if __name__ == '__main__':
    print(analyze_absorbance_from_formula(
        formula={'Fe': 2, 'O': 3},
        energy=xraydb.xray_edge('Fe', 'K').energy,
        area=1.33
    ))

    # Prints:
    # {
    #     'mass_fractions': {'Fe': 0.6994307614270416, 'O': 0.3005692385729583}, 
    #     'absorbance_steps': {'Fe': 2.222799182793335, 'O': 2.3062399460967837e-07},
    #     'mass_total(mg)': 12.123291571370844, 
    #     'mass_components(mg)': {'Fe': 8.479403054765946, 'O': 3.643888516604898}
    # }

```

The comparable output of XAFSmass is below. The results differ slightly from XAFSmass because this uses the Elam tables instead of Chantler and the evaluated energy positions are handled slightly differently.
![Fe2O3_example](https://user-images.githubusercontent.com/59660036/117896837-4fd24f00-b276-11eb-9903-81f9589edaac.png)

**Comment by newville** [comment]
@easyXAFS Oh, that's a good idea.  If I recall, Hephaestus could also report a 1-absorption length thickness and sample mass per cm^2 - that is super convenient.   If you're up for making a PR, I'll happily merge that.  

I think that would be a nice addition to the web app at https://xraydb.xrayabsorption.org/ (code at https://github.com/xraypy/xrayweb).   I'd be willing to add that to the web interface.

**Comment by easyXAFS** [comment]
@newville Thanks for the quick reply! Yes exactly it is similar to the Hephaestus calculation as well.

I will clean up the interface a little more and submit a PR. Before I do that, I will add a little bit more functionality for handling more generic sample specifications. For example, XAFSmass allows you to specify the weight percentages of some components, and then fill in the remainder (for example Mn%0.5(SiO2) where the rest of the material is SiO2). Also making use of xraydb chemparse for handling strings would be nice as well.

I agree, having it on the web app would be awesome and fit naturally next to the X-ray Flux page perhaps. I can help with the web interface as well.

**Comment by easyXAFS** [comment]
Submitted PR #16
