### ISSUE TITLE
Roughness in the Mirror Reflectivity doesn't seem to work

### ISSUE THREAD

**Issue by gbzan** [xraypy/XrayDB#17]
The output in the plot  is same whe I change the Roughness number in the mirror Reflectivity.

**Comment by newville** [comment]
@gbzan Thanks.  Well, I get:

```
>>> from xraydb.xray import mirror_reflectivity
>>> mirror_reflectivity('Pt', 0.003, 10000, roughness=0)
0.9475437465496794
>>> mirror_reflectivity('Pt', 0.003, 10000, roughness=100)
0.9146425155564538

```

So it is doing something.....   But the current calculation is wrong (this could really use a review!) because it's missing a factor of (2pi/lambda)**2 in the exponent.  The reflectivity for 100 Ang roughness at 10keV should be ~0.38, not ~0.9.

Will fix.

**Comment by gbzan** [comment]
Thank for fixing the scale for roughness in mirror reflectivity. It's very useful.
