### ISSUE TITLE
There is no Magnesium (Mg) element in the part of X-ray Attenuation of Materials

### ISSUE THREAD

**Issue by gbzan** [xraypy/XrayDB#18]
1. Could you please double check whether the software has Magnesium element in the part of X-ray Attenuation of Materials?
2. Is it possible to add the Chemical Formula or atomic number for element in drop-down box? It is a easy way to find the element. 
![image](https://user-images.githubusercontent.com/32512895/132041600-9672ea64-1660-46ca-b225-18bc2d9eda1d.png)

**Comment by newville** [comment]
@gbzan the drop-down list of "known materials" on that page is definitely a selected list.  You can enter any formula and density - that list just fills those values for you.

I guess I would say that we cannot make that list complete, we probably don't want a list of 1000 compounds. 

Should we add magnesium?  I don't have a strong opinion.  But, isn't Mg highly reactive? Do people (perhaps you) actually put Mg into X-ray beams?

**Comment by gbzan** [comment]
Thank you.  I understand we cann't put all the materials in the list. But my concern is that it's better to put the elements in the element table into the list.  Please add the Magnesium. Actually we are interested in the Mg/Al alloy.

**Comment by newville** [comment]
@gbzan Can you confirm that you understand that you can write "Mg" into the "Chemical formula" field and "1.738" in the density field, and that will show the attenuation for Mg metal?

If you are actually interested in Mg/Al alloys, you can also enter a chemical formula like "Mg0.2Al0.8" and give the appropriate density. 

The "known materials list" includes a small selection of materials commonly used for filters, attenuators, sample holders, and so forth that might actually be stuck in an X-ray beam. All that selecting one of those does is fill in the "chemical formula" and "density" entries.  But you can enter any material you want.

**Comment by gbzan** [comment]
Thank you. I already finished the job by manully input the formula and density. So I confirm that I understand that I can write "Mg" into the "Chemical formula" field and "1.738" in the density field, and that will show the attenuation for Mg metal.   Before I think we should put all the elements in the element talble into the list.  If you think it is not worth adding "Mg", let's forget it. Thank you all the same.
