### ISSUE TITLE
Error with python interface

### ISSUE THREAD

**Issue by luriol** [xraypy/XrayDB#2]
I am getting a error that the 'atomic_number' is not an attribute with the python interface.  e.g.

f = xdb.atomic_number('Si')
Traceback (most recent call last):

  File "<ipython-input-12-332dece126da>", line 1, in <module>
    f = xdb.atomic_number('Si')

  File "/home/luriol/anaconda3/lib/python3.7/site-packages/xraydb/xraydb.py", line 373, in atomic_number
    return self._elem_data(element).atomic_number

AttributeError: 'ElementData' object has no attribute 'atomic_number'

**Comment by newville** [comment]
@luriol  Sorry and thanks!  I guess I was only testing

```
 import xraydb
 f  = xraydb.atomic_number('Si')
```

but not the older usage of 
```
 import xraydb
xdb = xraydb.XrayDB()
 f  = xdb.atomic_number('Si')
```

I'll fix this.   And add more tests!

**Comment by luriol** [comment]
Thanks very much.  This works now.
