### ISSUE TITLE
`beta` value in `xray_delta_beta` is inconsistent with other tools

### ISSUE THREAD

**Issue by Corwinpro** [xraypy/XrayDB#20]
There was a change introduced in 3bf1923f47ad89434564de12e0bd0d45a21b8f3b and f5b185b83285aebd87085f280625e059af869b17 , and the `beta` array of values:

https://github.com/xraypy/XrayDB/blob/5f8a2a9bc84616ebb14483b1981e984f8c7fee08/python/tests/test_xray.py#L509

is not used in the `xray_delta_beta` test anymore.

The problem is that the `beta` array was consistent with the other tools such as [this one](https://henke.lbl.gov/optical_constants/getdb2.html), and the new `beta_photo` values are not. This is because the second output value of `xray_delta_beta` does not match the results of those external tools.

Is it possible to get information about the change introduced in the aforementioned commits, and how to produce results consistent with the [external tool](https://henke.lbl.gov/optical_constants/getdb2.html) using `xraydb`?

Thank you!

**Comment by newville** [comment]
@Corwinpro Hm, I don't see much difference in delta or beta between these versions or between the data from LBL. The returned attenuation length has a larger difference, which I think is the difference between using `beta_photo` v `beta_total` (attenuation vs photo-absorption). 

What is the size of the difference you see?  Can you give an example?

**Comment by Corwinpro** [comment]
Thank you @newville !

Sure, for example:

```python
import xraydb
xraydb.xray_delta_beta("I", 2.0, 90)
(0.022267960180854404, 0.01405226705927638, 7.801280250158834e-06)
```

And [this resource](https://henke.lbl.gov/optical_constants/getdb2.html) suggests something quite different:

```
I Density=2.
 Energy(eV), Delta, Beta
  90.  0.00345141697  0.0237003937
```

Do you think I am missing something? I hope I interpreted the results correctly, so `xraydb` predicts `0.022267960180854404` for \delta while the other source gives `0.00345141697` (and `0.01405226705927638` vs `0.0237003937` for \beta, respectively).

Also, with regards to the test changes that I refer to in the issue description: the old test values (`beta` array) presumes that for `Fe2O3` at `5.25` density the value is `4.15330456e-07`, and the new test values (the `beta_photo` array) uses `3.90526978e-07`. The external tool yields

```
Fe2O3 Density=5.25
 Energy(eV), Delta, Beta
  6500.  2.32142611E-05  4.15941031E-07
```

which is closer to the old (`beta`) value.

Thank you!
