### ISSUE TITLE
tool.setuptools_scm section in pyproject.toml contains incorrect information

### ISSUE THREAD

**Issue by reneeotten** [xraypy/XrayDB#26]
hi @newville, when trying to update the Python package in MacPorts we did run into an issue when downloading the package from PyPI and trying to build it use the provided `pyproject.toml` file.

It tries to write the version to:
```
[tool.setuptools_scm]
root = ".."
write_to = "python/xraydb/version.py"
version_scheme = "post-release"
```

the `write_to` here is incorrect, as there is not "python" directory in the tarball from PyPI (that path is only correct in the GitHub repository. It does work when I remove the `root` and "python/" from the `write_to` field.

**Comment by newville** [comment]
@reneeotten Yeah, I sort of suspect something is not very well tested with this scenario (ie, where Python root folder with `pyproject.toml` is not at the top of the github tree), maybe with some versions of setuptools?? 

I think I may need to change this project to not use `setuptools_scm` (maybe back to versioneer?) which is really, really sad.  
It's one of the only projects I have that is set up this way...
