### ISSUE TITLE
Mn not recognized

### ISSUE THREAD

**Issue by goodwin2208** [xraypy/XrayDB#29]
When using material_mu the element "Mn" is not recognized as a material but appears in the atomic density database.

**Comment by newville** [comment]
@goodwin2208 sorry for the delay in responding, but I cannot reproduce a problem here.

```python
>>> import xraydb
>>> xraydb.material_mu('Mn', energy=8000, density=7.2)
1968.785994041684
```

if you are still having trouble, please give more details of what you are doing and any error messages.

**Comment by goodwin2208** [comment]
I can no longer reproduce it either. I did change over to Conda in the meantime. I guess it was just a problem on my end. Thanks!
