### ISSUE TITLE
Index error for mu_elam for high energies

### ISSUE THREAD

**Issue by Spoon11581** [xraypy/XrayDB#30]
When inputting values just above 800keV for energies, I get an index error message.

**Comment by newville** [comment]
@Spoon11581 Thanks -- and I see that the Elam tables stop at 800 keV too.  They should go (as do the Chantler tables) to 1000 keV.

I'll look into fixing this.   And, we should also add a warning for Energy > 1 MeV.   Neither of these tables will be good above 1.022 MeV (2*m_e), as they all ignore pair production.

**Comment by newville** [comment]
@Spoon11581 I think this is now fixed in the master branch, warning but not failing when given energies > 800 keV.
