### ISSUE TITLE
Possible database error for atomic_densities

### ISSUE THREAD

**Issue by luriol** [xraypy/XrayDB#7]
I was using the xraydb program to retrieve the atomic_density of gold via
import xraydb
gold_density = xraydb.atomic_density('Au')

This yields a value of 18.85.  But the density of gold is 19.3.  Is this an error in the database, or am I misinterpreting the function?

**Comment by newville** [comment]
@luriol Thanks.  That is the value in Elam, et al source data file, and that is pretty far off.  
I'll check the other density values too - we should probably take those from a better source.

**Comment by luriol** [comment]
Matt,


Thanks for checking.


Larry

On July 15, 2020 at 9:08 AM, Matt Newville <notifications@github.com> wrote:






@luriol Thanks. That is the value in Elam, et al source data file, and that is pretty far off.
I'll check the other density values too - we should probably take those from a better source.
